name: kmong
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  camera: ^0.10.5+4
  flutter:
    sdk: flutter
  image: ^4.0.17
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner:
  build_runner:

flutter:
  uses-material-design: true
